CREATE CONSTRAINT company_id IF NOT EXISTS FOR (c:Company) REQUIRE c.id IS UNIQUE;
CREATE CONSTRAINT person_id  IF NOT EXISTS FOR (p:Person)  REQUIRE p.id IS UNIQUE;
CREATE CONSTRAINT email_addr IF NOT EXISTS FOR (e:Email)   REQUIRE e.address IS UNIQUE;

